from bot.commands.base import BaseCommand
from bot.commands.start import StartCommand
from bot.commands.message_to_admin import MessageToAdminCommand
from bot.commands.help import HelpCommand
from bot.commands.connect import ConnectCommand
from bot.commands.disconnect import DisconnectCommand
from bot.commands.chats import Chats
from bot.commands.history import History
from bot.commands.remove_chat import RemoveChat
