# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 17:03
from __future__ import unicode_literals

from django.db import migrations, models


def fill_is_active(*args, **kwargs):
    from chat.models import Chat
    for c in Chat.objects.all():
        c.telegram_active = c.is_active
        c.vk_active = c.is_active
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='telegram_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='vk_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(fill_is_active),
    ]
